USE heritage_db;

-- Auto-generated from city_raw.tsv: province/city only, deduplicated, English names
INSERT INTO china_cities (province, city) VALUES
('Anhui', 'Anqing'),
('Anhui', 'Bengbu'),
('Anhui', 'Bozhou'),
('Anhui', 'Chizhou'),
('Anhui', 'Chuzhou'),
('Anhui', 'Fuyang'),
('Anhui', 'Hefei'),
('Anhui', 'Huaibei'),
('Anhui', 'Huainan'),
('Anhui', 'Huangshan'),
('Anhui', 'Lu an'),
('Anhui', 'Maanshan'),
('Anhui', 'Suzhou (Anhui)'),
('Anhui', 'Tongling'),
('Anhui', 'Wuhu'),
('Anhui', 'Xuancheng'),
('Beijing', 'Beijing'),
('Chongqing', 'Chongqing'),
('Fujian', 'Fuzhou'),
('Fujian', 'Longyan'),
('Fujian', 'Nanping'),
('Fujian', 'Ningde'),
('Fujian', 'Putian'),
('Fujian', 'Quanzhou'),
('Fujian', 'Sanming'),
('Fujian', 'Xiamen'),
('Fujian', 'Zhangzhou'),
('Gansu', 'Baiyin'),
('Gansu', 'Dingxi'),
('Gansu', 'Gannan'),
('Gansu', 'Jiayuguan'),
('Gansu', 'Jinchang'),
('Gansu', 'Jiuquan'),
('Gansu', 'Lanzhou'),
('Gansu', 'Linxia'),
('Gansu', 'Longnan'),
('Gansu', 'Pingliang'),
('Gansu', 'Qingyang'),
('Gansu', 'Tianshui'),
('Gansu', 'Wuwei'),
('Gansu', 'Zhangye'),
('Guangdong', 'Chaozhou'),
('Guangdong', 'Dongguan'),
('Guangdong', 'Foshan'),
('Guangdong', 'Guangzhou'),
('Guangdong', 'Heyuan'),
('Guangdong', 'Huizhou'),
('Guangdong', 'Jiangmen'),
('Guangdong', 'Jieyang'),
('Guangdong', 'Maoming'),
('Guangdong', 'Meizhou'),
('Guangdong', 'Qingyuan'),
('Guangdong', 'Shantou'),
('Guangdong', 'Shanwei'),
('Guangdong', 'Shaoguan'),
('Guangdong', 'Shenzhen'),
('Guangdong', 'Yangjiang'),
('Guangdong', 'Yunfu'),
('Guangdong', 'Zhanjiang'),
('Guangdong', 'Zhaoqing'),
('Guangdong', 'Zhongshan'),
('Guangdong', 'Zhuhai'),
('Guangxi', 'Baise'),
('Guangxi', 'Beihai'),
('Guangxi', 'Chongzuo'),
('Guangxi', 'Fangchenggang'),
('Guangxi', 'Guigang'),
('Guangxi', 'Guilin'),
('Guangxi', 'Hechi'),
('Guangxi', 'Hezhou'),
('Guangxi', 'Laibin'),
('Guangxi', 'Liuzhou'),
('Guangxi', 'Nanning'),
('Guangxi', 'Qinzhou'),
('Guangxi', 'Wuzhou'),
('Guangxi', 'Yulin'),
('Guizhou', 'Anshun'),
('Guizhou', 'Bijie'),
('Guizhou', 'Guiyang'),
('Guizhou', 'Liupanshui'),
('Guizhou', 'Qiandongnan'),
('Guizhou', 'Qiannan'),
('Guizhou', 'Qianxinan'),
('Guizhou', 'Tongren'),
('Guizhou', 'Zunyi'),
('Hainan', 'Baisha'),
('Hainan', 'Baoting'),
('Hainan', 'Changjiang'),
('Hainan', 'Chengmai'),
('Hainan', 'Danzhou'),
('Hainan', 'Dingan'),
('Hainan', 'Dongfang'),
('Hainan', 'Haikou'),
('Hainan', 'Ledong'),
('Hainan', 'Lingao'),
('Hainan', 'Lingshui'),
('Hainan', 'Qionghai'),
('Hainan', 'Qiongzhong'),
('Hainan', 'Sansha'),
('Hainan', 'Sanya'),
('Hainan', 'Tunchang'),
('Hainan', 'Wanning'),
('Hainan', 'Wenchang'),
('Hainan', 'Wuzhishan'),
('Hebei', 'Baoding'),
('Hebei', 'Cangzhou'),
('Hebei', 'Chengde'),
('Hebei', 'Handan'),
('Hebei', 'Hengshui'),
('Hebei', 'Langfang'),
('Hebei', 'Qinhuangdao'),
('Hebei', 'Shijiazhuang'),
('Hebei', 'Tangshan'),
('Hebei', 'Xingtai'),
('Hebei', 'Zhangjiakou'),
('Heilongjiang', 'Daqing'),
('Heilongjiang', 'Daxinganling'),
('Heilongjiang', 'Harbin'),
('Heilongjiang', 'Hegang'),
('Heilongjiang', 'Heihe'),
('Heilongjiang', 'Jiamusi'),
('Heilongjiang', 'Jixi'),
('Heilongjiang', 'Mudanjiang'),
('Heilongjiang', 'Qiqihar'),
('Heilongjiang', 'Qitaihe'),
('Heilongjiang', 'Shuangyashan'),
('Heilongjiang', 'Suihua'),
('Heilongjiang', 'Yichun (Heilongjiang)'),
('Henan', 'Anyang'),
('Henan', 'Hebi'),
('Henan', 'Jiaozuo'),
('Henan', 'Jiyuan'),
('Henan', 'Kaifeng'),
('Henan', 'Luohe'),
('Henan', 'Luoyang'),
('Henan', 'Nanyang'),
('Henan', 'Pingdingshan'),
('Henan', 'Puyang'),
('Henan', 'Sanmenxia'),
('Henan', 'Shangqiu'),
('Henan', 'Xinxiang'),
('Henan', 'Xinyang'),
('Henan', 'Xuchang'),
('Henan', 'Zhengzhou'),
('Henan', 'Zhoukou'),
('Henan', 'Zhumadian'),
('Hong Kong', 'Hong Kong'),
('Hubei', 'Enshi'),
('Hubei', 'Ezhou'),
('Hubei', 'Huanggang'),
('Hubei', 'Huangshi'),
('Hubei', 'Jingmen'),
('Hubei', 'Jingzhou'),
('Hubei', 'Qianjiang'),
('Hubei', 'Shennongjia'),
('Hubei', 'Shiyan'),
('Hubei', 'Suizhou'),
('Hubei', 'Tianmen'),
('Hubei', 'Wuhan'),
('Hubei', 'Xiangyang'),
('Hubei', 'Xianning'),
('Hubei', 'Xiantao'),
('Hubei', 'Xiaogan'),
('Hubei', 'Yichang'),
('Hunan', 'Changde'),
('Hunan', 'Changsha'),
('Hunan', 'Chenzhou'),
('Hunan', 'Hengyang'),
('Hunan', 'Huaihua'),
('Hunan', 'Loudi'),
('Hunan', 'Shaoyang'),
('Hunan', 'Xiangtan'),
('Hunan', 'Xiangxi'),
('Hunan', 'Yiyang'),
('Hunan', 'Yongzhou'),
('Hunan', 'Yueyang'),
('Hunan', 'Zhangjiajie'),
('Hunan', 'Zhuzhou'),
('Inner Mongolia', 'Alxa'),
('Inner Mongolia', 'Baotou'),
('Inner Mongolia', 'Bayan Nur'),
('Inner Mongolia', 'Chifeng'),
('Inner Mongolia', 'Hinggan'),
('Inner Mongolia', 'Hohhot'),
('Inner Mongolia', 'Hulunbuir'),
('Inner Mongolia', 'Ordos'),
('Inner Mongolia', 'Tongliao'),
('Inner Mongolia', 'Ulanqab'),
('Inner Mongolia', 'Wuhai'),
('Inner Mongolia', 'Xilingol'),
('Jiangsu', 'Changzhou'),
('Jiangsu', 'Huai an'),
('Jiangsu', 'Lianyungang'),
('Jiangsu', 'Nanjing'),
('Jiangsu', 'Nantong'),
('Jiangsu', 'Suqian'),
('Jiangsu', 'Suzhou'),
('Jiangsu', 'Taizhou (Jiangsu)'),
('Jiangsu', 'Wuxi'),
('Jiangsu', 'Xuzhou'),
('Jiangsu', 'Yancheng'),
('Jiangsu', 'Yangzhou'),
('Jiangsu', 'Zhenjiang'),
('Jiangxi', 'Fuzhou (Jiangxi)'),
('Jiangxi', 'Ganzhou'),
('Jiangxi', 'Ji an'),
('Jiangxi', 'Jingdezhen'),
('Jiangxi', 'Jiujiang'),
('Jiangxi', 'Nanchang'),
('Jiangxi', 'Pingxiang'),
('Jiangxi', 'Shangrao'),
('Jiangxi', 'Xinyu'),
('Jiangxi', 'Yichun (Jiangxi)'),
('Jiangxi', 'Yingtan'),
('Jilin', 'Baicheng'),
('Jilin', 'Baishan'),
('Jilin', 'Changchun'),
('Jilin', 'Jilin City'),
('Jilin', 'Liaoyuan'),
('Jilin', 'Siping'),
('Jilin', 'Songyuan'),
('Jilin', 'Tonghua'),
('Jilin', 'Yanbian'),
('Liaoning', 'Anshan'),
('Liaoning', 'Benxi'),
('Liaoning', 'Chaoyang'),
('Liaoning', 'Dalian'),
('Liaoning', 'Dandong'),
('Liaoning', 'Fushun'),
('Liaoning', 'Fuxin'),
('Liaoning', 'Huludao'),
('Liaoning', 'Jinzhou'),
('Liaoning', 'Liaoyang'),
('Liaoning', 'Panjin'),
('Liaoning', 'Shenyang'),
('Liaoning', 'Tieling'),
('Liaoning', 'Yingkou'),
('Macau', 'Macau'),
('Ningxia', 'Guyuan'),
('Ningxia', 'Shizuishan'),
('Ningxia', 'Wuzhong'),
('Ningxia', 'Yinchuan'),
('Ningxia', 'Zhongwei'),
('Qinghai', 'Golog'),
('Qinghai', 'Haibei'),
('Qinghai', 'Haidong'),
('Qinghai', 'Hainan (Qinghai)'),
('Qinghai', 'Haixi'),
('Qinghai', 'Huangnan'),
('Qinghai', 'Xining'),
('Qinghai', 'Yushu'),
('Shaanxi', 'Ankang'),
('Shaanxi', 'Baoji'),
('Shaanxi', 'Hanzhong'),
('Shaanxi', 'Shangluo'),
('Shaanxi', 'Tongchuan'),
('Shaanxi', 'Weinan'),
('Shaanxi', 'Xi an'),
('Shaanxi', 'Xianyang'),
('Shaanxi', 'Yan an'),
('Shaanxi', 'Yulin (Shaanxi)'),
('Shandong', 'Binzhou'),
('Shandong', 'Dezhou'),
('Shandong', 'Dongying'),
('Shandong', 'Heze'),
('Shandong', 'Jinan'),
('Shandong', 'Jining'),
('Shandong', 'Liaocheng'),
('Shandong', 'Linyi'),
('Shandong', 'Qingdao'),
('Shandong', 'Rizhao'),
('Shandong', 'Tai an'),
('Shandong', 'Weifang'),
('Shandong', 'Weihai'),
('Shandong', 'Yantai'),
('Shandong', 'Zaozhuang'),
('Shandong', 'Zibo'),
('Shanxi', 'Changzhi'),
('Shanxi', 'Datong'),
('Shanxi', 'Jincheng'),
('Shanxi', 'Jinzhong'),
('Shanxi', 'Linfen'),
('Shanxi', 'Lvliang'),
('Shanxi', 'Shuozhou'),
('Shanxi', 'Taiyuan'),
('Shanxi', 'Xinzhou'),
('Shanxi', 'Yangquan'),
('Shanxi', 'Yuncheng'),
('Sichuan', 'Aba'),
('Sichuan', 'Bazhong'),
('Sichuan', 'Chengdu'),
('Sichuan', 'Dazhou'),
('Sichuan', 'Deyang'),
('Sichuan', 'Garze'),
('Sichuan', 'Guang an'),
('Sichuan', 'Guangyuan'),
('Sichuan', 'Leshan'),
('Sichuan', 'Liangshan'),
('Sichuan', 'Luzhou'),
('Sichuan', 'Meishan'),
('Sichuan', 'Mianyang'),
('Sichuan', 'Nanchong'),
('Sichuan', 'Neijiang'),
('Sichuan', 'Panzhihua'),
('Sichuan', 'Suining'),
('Sichuan', 'Ya an'),
('Sichuan', 'Yibin'),
('Sichuan', 'Zigong'),
('Sichuan', 'Ziyang'),
('Taiwan', 'Changhua'),
('Taiwan', 'Chiayi City'),
('Taiwan', 'Chiayi County'),
('Taiwan', 'Hsinchu City'),
('Taiwan', 'Hsinchu County'),
('Taiwan', 'Hualien'),
('Taiwan', 'Kaohsiung'),
('Taiwan', 'Keelung'),
('Taiwan', 'Miaoli'),
('Taiwan', 'Nantou'),
('Taiwan', 'New Taipei'),
('Taiwan', 'Penghu'),
('Taiwan', 'Pingtung'),
('Taiwan', 'Taichung'),
('Taiwan', 'Tainan'),
('Taiwan', 'Taipei'),
('Taiwan', 'Taitung'),
('Taiwan', 'Taoyuan'),
('Taiwan', 'Yilan'),
('Taiwan', 'Yunlin'),
('Tianjin', 'Tianjin'),
('Tibet', 'Chamdo'),
('Tibet', 'Lhasa'),
('Tibet', 'Nagqu'),
('Tibet', 'Ngari'),
('Tibet', 'Nyingchi'),
('Tibet', 'Shannan'),
('Tibet', 'Shigatse'),
('Xinjiang', 'Aksu'),
('Xinjiang', 'Altay'),
('Xinjiang', 'Aral'),
('Xinjiang', 'Bayingolin'),
('Xinjiang', 'Beitun'),
('Xinjiang', 'Bortala'),
('Xinjiang', 'Changji'),
('Xinjiang', 'Hami'),
('Xinjiang', 'Hotan'),
('Xinjiang', 'Huyanghe'),
('Xinjiang', 'Ili'),
('Xinjiang', 'Karamay'),
('Xinjiang', 'Kashgar'),
('Xinjiang', 'Kizilsu'),
('Xinjiang', 'Kokdala'),
('Xinjiang', 'Kunyu'),
('Xinjiang', 'Shihezi'),
('Xinjiang', 'Shuanghe'),
('Xinjiang', 'Tacheng'),
('Xinjiang', 'Tiemenguan'),
('Xinjiang', 'Tumxuk'),
('Xinjiang', 'Turpan'),
('Xinjiang', 'Urumqi'),
('Xinjiang', 'Wujiaqu'),
('Xinjiang', 'Xinxing'),
('Yunnan', 'Baoshan'),
('Yunnan', 'Chuxiong'),
('Yunnan', 'Dali'),
('Yunnan', 'Dehong'),
('Yunnan', 'Diqing'),
('Yunnan', 'Honghe'),
('Yunnan', 'Kunming'),
('Yunnan', 'Lijiang'),
('Yunnan', 'Lincang'),
('Yunnan', 'Nujiang'),
('Yunnan', 'Pu er'),
('Yunnan', 'Qujing'),
('Yunnan', 'Wenshan'),
('Yunnan', 'Xishuangbanna'),
('Yunnan', 'Yuxi'),
('Yunnan', 'Zhaotong'),
('Zhejiang', 'Hangzhou'),
('Zhejiang', 'Huzhou'),
('Zhejiang', 'Jiaxing'),
('Zhejiang', 'Jinhua'),
('Zhejiang', 'Lishui'),
('Zhejiang', 'Ningbo'),
('Zhejiang', 'Quzhou'),
('Zhejiang', 'Shaoxing'),
('Zhejiang', 'Taizhou (Zhejiang)'),
('Zhejiang', 'Wenzhou'),
('Zhejiang', 'Zhoushan');
